[versions]
assertj = "3.19.0"
junit = "5.12.0"
testcontainers = "1.20.5"
wiremock = "3.12.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-wiremock = { module = "org.wiremock.integrations.testcontainers:wiremock-testcontainers-module", version = "1.0-alpha-13" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }

[plugins]
gradle-test-logger = { id = "com.adarshr.test-logger", version = "4.0.0" }
